### ISSUE TITLE
Are variables set to an integer type generated in a normal distribution?

### ISSUE THREAD

**Issue by gihunjin** [Team-TUD/CTAB-GAN-Plus#5]
I analyzed the Likert 5-point scale as an integer type. Even though my actual data is not a normal distribution, the synthetic data created a normal distribution. Why is this happening?

**Comment by zhao-zilong** [comment]
Hi @gihunjin no, only the variable that put into the "general_transform" may have that effect, otherwise the continuous variable distribution is approximated by variational gaussian mixture.

**Comment by gihunjin** [comment]
![image](https://user-images.githubusercontent.com/132451113/236119279-d0029b07-b103-4333-8220-3c7adc813d9c.png)

This is the probability density function of the mean of variables when I specify my variables as an integer type.

**Comment by zhao-zilong** [comment]
Hi @gihunjin  it seems that your variable is not "integer" type. And for continuous variable, CTAB-GAN+ should have similar performance as CTGAN since we all use variational gaussian mixture. Did you try to remove it from integer? I can only see this happens when it is in the "general_transform" type.

**Comment by gihunjin** [comment]
Unfortunately, I designated all 42 questions on a 5-point scale as "integer" type. Rather, setting all the questions as categorical showed better performance

**Comment by zhao-zilong** [comment]
Hi @gihunjin  I don't know if I have answered your question. So to indicate any variable as integer type, our code only treat the column as continuous, just in the post-processing period, we transform its value from float to integer. I think the reason you treat column as continuous instead of categorical is because of the dimensionality issue right?

**Comment by gihunjin** [comment]
Yes, it is also for dimensionality to consider a five-point scale as continuous in the field of psychology in general. But sometimes there's still a debate about whether it's categorical or continuous. What I'm curious about is why the synthetic data appears as a normal distribution when set to an integer type.

**Comment by zhao-zilong** [comment]
@gihunjin just have a thought on why it has a normal distribution like that, because when you change from float to integer, you don't really do ROUNDING, no matter the values it's generated between 3 and 4 will be translated to 3 but apparently in your case, 3.8 should be rounded to 4. Maybe you can let it as just simple continuous and round it later yourself.

**Comment by gihunjin** [comment]
I don't know if I understand you well, but I've never rounded up the responses. The responses of the questions existed in an integer form from the beginning. For example, the first variable is, "Are you depressed recently?"If so, the responses are 1, 2, 3, 4, and 5 indicating the intensity of depression.

**Comment by gihunjin** [comment]
Do you mean that the researcher's model converts the number between 3 and 4 to 3?

**Comment by zhao-zilong** [comment]
@gihunjin  yeah, I understand the original value is in the integer format, but because you didn't indicate they are categorical, CTAB-GAN+ will treat it as continuous, then the generated value are not exactly 3 or 4, it can be 3.88. And if you indicate the value is "integer", it will transfer the float to integer, so Int(3.88) will be 3 instead of 4, this is how the int() function works in python.

**Comment by gihunjin** [comment]
Thank you for your effort. I will also try to find out what this is different from CTGAN.
