### ISSUE TITLE
Query regarding Support for incremental training and monitoring losses in CTABGAN+

### ISSUE THREAD

**Issue by yash-rathore-arya** [Team-TUD/CTAB-GAN-Plus#9]
Does CTABGAN+ support incremental training? Suppose I have a dataset with 300,000 rows and I train the model initially on the first 5,000 rows. If I save the model, load it again, and continue training it on the next 5,000 rows, will the model start from scratch or resume training with the weights it previously learned?

Additionally, I would like to inquire about the availability of information regarding the Generator and Discriminator losses during the training phase. Since these losses are not explicitly printed, I am uncertain about the model's progress. Please provide more details on whether incremental training is supported by CTABGAN+ and how to monitor the Generator and Discriminator losses in this model.

**Comment by zhao-zilong** [comment]
Hi @yash-rathore-arya 

Sorry for the late reply, I don't know why but I totally missed this question.

So for your first question. Of course, you can save it and load later. But I would doubt its performance. If you data is iid, maybe it's ok, otherwise I think you need to use some tricks to make sure when the model is trained on new data, it will not forget the old data pattern.

And for the monitoring of loss, we are currently not doing that. From my understand, generator and discriminator losses are not stable, maybe inspect classifier loss (it should constantly decreasing) can be a way to do that.

Best,

Zilong
